import { test, expect } from "@playwright/test";

for (const width of [390, 1440]) {
  test(`four sections, reported academics, reviewed imports and project chat at ${width}px`, async ({ page }) => {
    const errors = [];
    page.on("pageerror", e => errors.push(e.message));
    await page.setViewportSize({ width, height: 940 });
    await page.goto("/login");
    await page.getByRole("button", { name:"Create an account" }).click();
    await page.getByLabel("Name", { exact:true }).fill("Learner");
    await page.getByLabel("Email").fill(`four-sections-${width}@example.com`);
    await page.getByLabel("Password", { exact:true }).fill("four section password");
    await page.getByRole("button", { name:"Create account", exact:true }).click();
    const nav = page.getByRole("navigation", { name:"Personal navigation" });
    await expect(nav.getByRole("button")).toHaveText(["Chat","Dashboard","Coding stats","Practice"]);
    await nav.getByRole("button", { name:"Dashboard", exact:true }).click();
    await expect(page.getByText("Your semester story starts here.")).toBeVisible();
    await expect(page.locator(".academic-numbers strong")).toHaveText(["—","—"]);
    await page.screenshot({path:`test-results/dashboard-empty-${width}.png`,fullPage:true});
    await page.getByRole("button", { name:"Add academic details", exact:true }).click();
    await page.getByLabel("Program", { exact:true }).fill("CSE");
    await page.getByLabel("Current semester", { exact:true }).fill("3");
    await page.getByLabel("Total credits obtained", { exact:true }).fill("82");
    await page.getByLabel("Target SGPA", { exact:true }).fill("9");
    await page.getByRole("button", { name:"Save academic details", exact:true }).click();
    await expect(page.locator(".academic-numbers strong")).toHaveText(["82","9"]);
    await page.getByLabel("Result semester", { exact:true }).fill("1");
    await page.getByLabel("Reported SGPA", { exact:true }).fill("7.8");
    await page.getByRole("button", { name:"Save semester result", exact:true }).click();
    await expect(page.getByRole("img",{name:"Reported SGPA by semester"})).toBeVisible();
    await page.getByRole("button", { name:"Import image or PDF", exact:true }).click();
    await page.locator('.academic-import input[type="file"]').setInputFiles({name:"semester.pdf",mimeType:"application/pdf",buffer:Buffer.from("%PDF-fixture")});
    await page.getByRole("button", { name:"Review extracted data", exact:true }).click();
    await expect(page.locator(".subject-tiles")).toHaveCount(0);
    await page.locator(".import-review").getByLabel("Score",{exact:true}).fill("9");
    await page.getByRole("button", { name:"Confirm and save records", exact:true }).click();
    await expect(page.locator(".subject-tiles")).toContainText("Database Systems");
    await page.locator(".subject-tiles button").click();
    await expect(page.getByLabel("Subject syllabus")).toHaveValue(/SELECT/);
    await expect(page.locator(".syllabus-editor")).toContainText("9/10");
    await page.reload();
    await nav.getByRole("button",{name:"Dashboard",exact:true}).click();
    await expect(page.locator(".academic-numbers strong")).toHaveText(["82","9"]);
    await page.screenshot({path:`test-results/dashboard-filled-${width}.png`,fullPage:true});
    await nav.getByRole("button",{name:"Coding stats",exact:true}).click();
    await expect(page.locator(".coding-hero strong")).toHaveText(["—","—","—"]);
    await page.getByLabel("GitHub username",{exact:true}).fill("fixture-user");
    await page.getByRole("button",{name:"Connect GitHub",exact:true}).click();
    await expect(page.locator(".github-connection")).toContainText("6 public repositories");
    await nav.getByRole("button",{name:"Practice",exact:true}).click();
    await page.getByRole("button",{name:"Add project",exact:true}).click();
    await page.getByLabel("Project name",{exact:true}).fill("SQL learning");
    await page.getByLabel("Learning goal",{exact:true}).fill("Practise SQL from my own notes.");
    await page.getByRole("checkbox",{name:/Database Systems/}).check();
    await page.getByRole("button",{name:"Create project",exact:true}).click();
    await expect(page.locator(".project-detail")).toContainText("Linked subjects: Database Systems");
    await page.locator('.project-detail input[type="file"]').setInputFiles({name:"notes.txt",mimeType:"text/plain",buffer:Buffer.from("SQL SELECT reads rows.")});
    await expect(page.locator(".material-row")).toContainText("notes.txt");
    await page.getByLabel("Public GitHub repository",{exact:true}).fill("https://github.com/fixture/repo");
    await page.getByRole("button",{name:"Add repository",exact:true}).click();
    await expect(page.locator(".material-row")).toHaveCount(2);
    await page.screenshot({path:`test-results/projects-${width}.png`,fullPage:true});
    await page.getByRole("button",{name:"Chat about SQL learning",exact:true}).click();
    await expect(page.locator(".project-context")).toContainText("SQL learning");
    await page.getByLabel("Message",{exact:true}).fill("Explain SELECT from this project");
    await page.getByLabel("Message",{exact:true}).press("Enter");
    await expect(page.locator(".chat-message.assistant")).toContainText("SELECT reads rows");
    await page.getByLabel("Message",{exact:true}).fill("Explain SELECT again");
    await page.getByRole("button",{name:"Ask Orbit",exact:true}).click();
    await expect(page.locator(".tool-summary").last()).toContainText("1 cached");
    await page.screenshot({path:`test-results/project-chat-${width}.png`});
    await page.getByRole("button",{name:"Sign out",exact:true}).click();
    await page.getByLabel("Email").fill(`four-sections-${width}@example.com`);
    await page.getByLabel("Password",{exact:true}).fill("four section password");
    await page.getByRole("button",{name:"Sign in",exact:true}).click();
    await expect(page.locator(".chat-message.assistant")).toHaveCount(2);
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
    expect(errors).toEqual([]);
  });
}
