import { test, expect } from "@playwright/test";

for (const width of [390, 1440]) {
  test(`landing to reviewed paper and search at ${width}px`, async ({ page }) => {
    const errors = [];
    page.on("pageerror", e => errors.push(e.message));
    await page.setViewportSize({ width, height: 960 });
    await page.goto("/");
    await expect(page.getByRole("heading", {name: /A clearer view/})).toBeVisible();
    await page.evaluate(() => window.scrollTo(0, 0));
    await page.screenshot({ path: `test-results/landing-${width}.png`, fullPage: true });
    expect(await page.evaluate(()=>document.documentElement.scrollWidth <= innerWidth)).toBe(true);
    await page.getByRole("link", {name: "Create your workspace", exact: true}).first().click();
    await page.getByLabel("Name",{exact:true}).fill("Paper Student");
    await page.getByLabel("Email").fill(`paper-${width}@example.com`);
    await page.getByLabel("Password",{exact:true}).fill("a secure paper password");
    await page.getByRole("button",{name:"Create account",exact:true}).click();
    await page.getByLabel("Subject name").fill("Database systems");
    await page.getByLabel("Subject code").fill("CS301");
    await page.getByLabel("Semester").fill("3");
    await page.getByRole("button",{name:"Add subject",exact:true}).click();
    await expect(page.getByRole("listitem")).toContainText("Database systems");
    await page.getByRole("button",{name:"Papers",exact:true}).click();
    await page.evaluate(() => window.scrollTo(0, 0));
    await page.screenshot({path:`test-results/papers-empty-${width}.png`,fullPage:true});
    await page.getByRole("button",{name:"Upload your first paper"}).click();
    await page.getByLabel("Subject",{exact:true}).selectOption({label:"Database systems · CS301"});
    await page.getByLabel("Paper year").fill("2025");
    await page.getByLabel("Topics for this paper").fill("SQL, Normalization");
    await page.locator('input[type="file"]').setInputFiles({name:"Database-final-2025.txt",mimeType:"text/plain",buffer:Buffer.from("Database Systems\n1. Explain SQL outer join. [5 marks]\n2. Explain Normalization. [10 marks]")});
    await page.getByRole("button",{name:"Upload and extract"}).click();
    await expect(page.getByText("0/2 questions confirmed")).toBeVisible();
    await page.getByRole("button",{name:"Review questions"}).click();
    const cards=page.locator(".question-card");
    await cards.nth(0).getByLabel("Question text").fill("1. Explain SQL inner and outer joins. [5 marks]");
    await cards.nth(0).getByRole("button",{name:"Confirm question",exact:true}).click();
    await expect(cards.nth(0).getByText("Confirmed",{exact:true})).toBeVisible();
    await cards.nth(1).getByLabel("Marks",{exact:true}).fill("8");
    await cards.nth(1).getByRole("button",{name:"Confirm question",exact:true}).click();
    await expect(page.getByText("2026 · 2/2 confirmed · ready")).toBeVisible();
    await page.evaluate(() => window.scrollTo(0, 0));
    await page.screenshot({path:`test-results/papers-review-${width}.png`,fullPage:true});
    expect(await page.evaluate(()=>document.documentElement.scrollWidth <= innerWidth)).toBe(true);
    await page.getByRole("button",{name:"Search questions",exact:true}).click();
    await page.getByLabel("Search query").fill("SQL");
    await page.getByRole("button",{name:"Search confirmed questions"}).click();
    await expect(page.locator(".paper-result")).toHaveCount(1);
    await expect(page.locator(".paper-result")).toContainText("inner and outer joins");
    await page.evaluate(() => window.scrollTo(0, 0));
    await page.screenshot({path:`test-results/papers-search-${width}.png`,fullPage:true});
    await page.reload();
    await page.getByRole("button",{name:"Papers",exact:true}).click();
    await expect(page.getByText("2/2 questions confirmed")).toBeVisible();
    await page.getByRole("button",{name:"Delete paper",exact:true}).click();
    await page.getByRole("dialog").getByRole("button",{name:"Delete paper",exact:true}).click();
    await expect(page.getByRole("heading",{name:"Your next revision starts here."})).toBeVisible();
    expect(errors).toEqual([]);
  });
}
