import { useState } from "react";
import { Link } from "react-router-dom";
import { ArrowRight, ArrowUpRight, BookOpen, Check, Code2, FileText, MessageSquare, Plus } from "lucide-react";
import "./landing.css";

const records = [
  ["CIC-210", "Database management systems", "85", "Final result"],
  ["CIC-212", "Programming in Java", "87", "Final result"],
  ["CIC-206", "Theory of computation", "80", "Final result"],
  ["BS-202", "Probability & statistics", "74", "Final result"],
];
function WorkspacePreview() {
  const [tab,setTab]=useState("Records");
  return <div className="lp-preview" id="preview">
    <div className="lp-preview-title"><span><img className="lp-orbit-mark" src="/orbit-mark.svg" alt="" /> Orbit AI</span><span>EXAMPLE WORKSPACE</span><span className="lp-user">D</span></div>
    <div className="lp-preview-layout"><aside><span>WORKSPACE</span>{[["Records",BookOpen],["Papers",FileText],["Assistant",MessageSquare]].map(([name,Icon])=><button aria-pressed={tab===name} onClick={()=>setTab(name)} key={name}><Icon size={15}/>{name}</button>)}<small>Personal account<br/>Your data stays separate.</small></aside><div className="lp-preview-content">
      {tab==="Records" ? <><div className="lp-preview-heading"><div><p>SEMESTER 04</p><h2>Your subjects</h2></div><span>4 subjects</span></div><div className="lp-record-table"><div className="lp-table-head"><span>SUBJECT</span><span>MARK / 100</span></div>{records.map(([code,name,mark,kind])=><div className="lp-record-row" key={code}><div><small>{code}</small><strong>{name}</strong><span>{kind}</span></div><b>{mark}<span>/100</span></b></div>)}</div><div className="lp-preview-foot"><Check size={13}/> Every mark keeps its source and scale.</div></> : tab==="Papers" ? <><div className="lp-preview-heading"><div><p>QUESTION LIBRARY</p><h2>Check it. Then trust it.</h2></div><FileText size={20}/></div><div className="lp-preview-paper"><span>EXAMPLE QUESTION · PAGE 1</span><h3>Compare inner and outer joins with an example.</h3><div><span>Topic <b>Joins</b></span><span>Marks <b>6</b></span></div><p><Check size={14}/> Confirmed for your question library</p></div><p className="lp-preview-note">Extracted text stays out of search until you confirm it. Correct the wording, topic, or marks first.</p></> : <><div className="lp-preview-heading"><div><p>ASK ORBIT</p><h2>Start with a real question.</h2></div><MessageSquare size={20}/></div><div className="lp-example-message">What should I revisit in databases?</div><div className="lp-example-answer"><span>AN EXAMPLE OF AN EVIDENCE-BACKED ANSWER</span><p>Joins appears in your confirmed questions. Use one of those questions as a revision starting point.</p><p>A topic appearing often doesn’t mean you’re weak at it.</p><div><FileText size={13}/> Source question · page 1</div></div></>}
    </div></div>
  </div>;
}

export default function Landing({demo,onDemo,busy,error,signedIn}) {
  return <div className="lp">
    <header className="lp-nav"><Link to="/" className="lp-brand"><img src="/orbit-mark.svg" alt="" /> Orbit AI</Link><nav aria-label="Main navigation"><a href="#workspace">Workspace</a><a href="#papers">Past papers</a><a href="#approach">How it works</a></nav><Link to={signedIn ? "/dashboard" : "/login"} className="lp-signin">{signedIn ? "Open workspace" : "Sign in"}<ArrowUpRight size={15}/></Link></header>
    <main>
      <section className="lp-hero"><div className="lp-hero-copy"><p className="lp-label">THE PERSONAL STUDENT WORKSPACE</p><h1>A clearer view<br/>of the work<br/>you put in.</h1><p className="lp-intro">Your marks tell one part of the story.<br/>Your code, projects, and past papers tell the rest.<br/>Bring them together in Orbit.</p><div className="lp-hero-actions">{signedIn ? <Link className="lp-button" to="/dashboard">Open your workspace<ArrowRight size={17}/></Link> : <Link className="lp-button" to="/login?mode=register">Create your workspace<ArrowRight size={17}/></Link>}{demo && !signedIn ? <button className="lp-text-button" onClick={onDemo} disabled={busy}>{busy ? "Opening…" : "Open preloaded demo"}<ArrowUpRight size={15}/></button> : <a className="lp-text-button" href="#preview">Explore the workspace<ArrowUpRight size={15}/></a>}</div><p className="lp-small">Start with one subject. Add the rest as you go.</p>{error && <p role="alert" className="error">{error}</p>}</div><div className="lp-hero-product"><WorkspacePreview/><p className="lp-example-caption">A working preview of the idea. Select a section to explore.<span>01 — 03</span></p></div></section>
      <div className="lp-index"><span>ONE WORKSPACE, FOUR PARTS</span><a href="#workspace"><BookOpen size={15}/> Academic records</a><a href="#workspace"><Code2 size={15}/> Coding activity</a><a href="#workspace"><Plus size={15}/> Project work</a><a href="#papers"><FileText size={15}/> Past papers</a></div>
      <section className="lp-section" id="workspace"><div className="lp-section-top"><p className="lp-label">01 / THE RECORDS</p><h2>A semester is more<br/>than a final number.</h2><p>Keep the detail that gives a result meaning.<br/>The subject. The date. The scale. The source.</p></div><div className="lp-columns"><article><span>ACADEMICS</span><h3>Keep the full context.</h3><p>Add marks as they come in, or import them together. Compare results on the same scale without mixing formal marks with practice.</p></article><article><span>CODING</span><h3>See the effort over time.</h3><p>Connect a public coding profile or enter your totals. Saved snapshots stay available, even when the source won’t refresh.</p></article><article><span>PROJECTS</span><h3>Remember what you built.</h3><p>Save your role, repository, result, and reflection. A useful record of the work, beyond a certificate in a folder.</p></article></div></section>
      <section className="lp-paper-section" id="papers"><div className="lp-paper-copy"><p className="lp-label">02 / THE PAPER LIBRARY</p><h2>Put your past papers<br/>back to work.</h2><p>Upload a paper. Review the extracted questions.<br/>Find a topic when you need it.</p><p>You decide what enters your library. Correct a split question, fix its marks, or change its topic before confirming it.</p><a href="#preview">Explore the preview <ArrowUpRight size={16}/></a></div><div className="lp-paper-sheet"><div className="lp-sheet-header"><FileText size={20}/><span>DATABASE SYSTEMS<br/><small>Illustrative paper excerpt</small></span><span>01</span></div><div className="lp-sheet-question"><span>QUESTION 2</span><p>Explain normalization up to third normal form, using a suitable example.</p><div><span>Normalization</span><b>8 marks</b></div></div><div className="lp-sheet-review"><Check size={16}/><div><strong>Reviewed by you.</strong><small>Now available in your confirmed library.</small></div></div></div></section>
      <section className="lp-approach" id="approach"><div><p className="lp-label">03 / YOUR NEXT STEP</p><h2>Ask a question.<br/>Follow the evidence.</h2><p>“SQL test Friday. I have two hours.”</p><p>Orbit can read your marks and confirmed questions to help you choose what to revisit. Open the supporting records. Accept an action, or dismiss it.</p></div><ol><li><span>01</span><div><h3>Bring your own records.</h3><p>Your workspace starts empty. Add subjects, results, and the material you actually use.</p></div></li><li><span>02</span><div><h3>Check what matters.</h3><p>Confirm extracted questions. Keep dates and sources attached to your records.</p></div></li><li><span>03</span><div><h3>Choose the next action.</h3><p>Read the evidence behind a suggestion. Missing evidence stays missing; one mark isn’t a trend.</p></div></li></ol></section>
      <section className="lp-close"><div><p className="lp-label">YOUR WORK, IN ONE PLACE.</p><h2>Start with what you have.</h2></div><Link className="lp-button" to={signedIn ? "/dashboard" : "/login?mode=register"}>{signedIn ? "Open workspace" : "Create your workspace"}<ArrowRight size={18}/></Link></section>
    </main><footer className="lp-footer"><Link className="lp-brand" to="/"><img src="/orbit-mark.svg" alt="" /> Orbit AI</Link><p>Built around your records. Kept in your account.</p><a href="#">Back to top ↑</a></footer>
  </div>;
}
