import { useEffect, useState } from "react";
import { api, post } from "./api";
import EvidenceList from "./Evidence";
import "./insights.css";

export default function Suggestions(){
  const [rows,setRows]=useState([]),[state,setState]=useState("proposed"),[busy,setBusy]=useState(false),[error,setError]=useState(""),[loading,setLoading]=useState(true);
  useEffect(()=>{const c=new AbortController();api("/personal/suggestions",{signal:c.signal}).then(setRows).catch(e=>{if(!c.signal.aborted)setError(e.message);}).finally(()=>{if(!c.signal.aborted)setLoading(false);});return()=>c.abort();},[]);
  async function update(id,decision){setBusy(true);setError("");try{if(id){await api(`/personal/suggestions/${id}`,{method:"PUT",body:JSON.stringify({state:decision})});setRows(await api("/personal/suggestions"));}else{setRows(await post("/personal/suggestions/refresh",{}));}}catch(e){setError(e.message);}finally{setBusy(false);}}
  const shown=rows.filter(r=>r.state===state);
  return <section className="workspace-card suggestions-panel"><div className="section-heading"><div><p className="eyebrow">EVIDENCE → ACTION</p><h2>Your next actions</h2></div><button onClick={()=>update()} disabled={busy}>{busy ? "Updating…" : "Refresh suggestions"}</button></div><p>Revision ideas from confirmed questions and your own topic notes. Check the sources, then choose what to take on.</p><div className="suggestion-tabs" aria-label="Suggestion status">{[["proposed","To consider"],["accepted","Accepted"],["dismissed","Dismissed"]].map(([value,label])=><button key={value} aria-pressed={state===value} onClick={()=>setState(value)}>{label} <span>{rows.filter(r=>r.state===value).length}</span></button>)}</div>{error && <p className="error" role="alert">{error}</p>}{loading ? <p role="status">Reading suggestions…</p> : !shown.length ? <div className="suggestion-empty">{state === "proposed" ? "No new actions to consider. Confirm paper questions or add your own weak-topic notes, then refresh. Unchanged dismissed actions stay dismissed." : `No ${state} actions yet.`}</div> : shown.map(r=><article className="suggestion-item" key={r.id}><div className="suggestion-item-title"><h3>{r.title}</h3>{r.stale && <span>Sources changed</span>}</div><p>{r.text}</p><EvidenceList sources={r.evidence}/>{r.state === "proposed" && <div className="suggestion-actions"><button className="primary" disabled={busy || r.stale} onClick={()=>update(r.id,"accepted")}>Accept action</button><button disabled={busy} onClick={()=>update(r.id,"dismissed")}>Dismiss</button>{r.stale && <small>Refresh to review current evidence before accepting.</small>}</div>}</article>)}</section>;
}
